### ISSUE TITLE
Add parametric template functions to the library

### ISSUE THREAD

**Issue by flelli** [mooltiverse/nyx#104]
So far we have [unparametrized functions available](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/templates/#functions) because [Mustache](https://mustache.github.io/) did not allow parameters but using [Handlebars](https://handlebarsjs.com/) in its place also opens to [custom helper functions](https://handlebarsjs.com/guide/#custom-helpers) that accept options/parameters.

While other functions may be useful, here are the ones that could be used in place of static ones:

- `short`: with a _length_ parameter we can use this one with arbitrary length instead of `short5`, `short6`, `short7`
- `timestamp`: with a _format_ parameter we can use this one with arbitrary format instead of `timestampISO8601`, `timestampYYYYMMDDHHMMSS`
- `environment`: with a _variable_ parameter we can return any environment variable instead of `environment.user`, `timestampYYYYMMDDHHMMSS`. There is actually the `environment.variable` function but this could be a more readable alias

Existing functions must still be available for backward compatibility.

Depends on #103

**Comment by boardbloke** [comment]
I've added a couple that wuld vbe useful in my use case -  https://github.com/mooltiverse/nyx/issues/119

**Comment by flelli** [comment]
Hi @boardbloke ,

So, trying to make them more generic, you need something like:

- a `truncate` function that lets you keep/discard everything before/after a certain match or position in a string
- a `substring` function that lets extract a portion from a string depending on character delimiters or positions (which is basically the same as above, but with 2 boundaries/delimiters)
- an `extract` function that, using a regular expression, lets you keep or discard a portion of a string based on a user defined regular expression

Is this correct?

**Comment by boardbloke** [comment]
Hi @flelli ,

I think that would cover it, yes.

Thanks again for the quick response!

**Comment by flelli** [comment]
New functions `capture`, `cutLeft`, `cutRight`, `replace`, `timeFormat` have been implemented and will be available with the upcoming `2.0.0` release. See #138

**Comment by flelli** [comment]
Available in release [2.0.0](https://github.com/mooltiverse/nyx/releases/tag/2.0.0).
