### ISSUE TITLE
Request for additional functions to manipulate branch names for version strings

### ISSUE THREAD

**Issue by boardbloke** [mooltiverse/nyx#119]
See also https://github.com/mooltiverse/nyx/issues/118

The rationale for this is that I ideally want to be able to have feature branches that look like "feature/[jira-id]_some_helpful_text", e.g. "feature/ABCD-1234_fix_breaking_widget" but have that turn into a version that looks like either "build-1.0.1-feature_ABCD1234" or "build-1.0.1-ABCD1234"

It seems That's not currently possible at the moment because I think would require some template functions that can:

1) strip git directories (i.e. trim leading characters in the branch name up to the final /)
2) strip trailing characters after a leading regex defined by config (so I could define a regex for jira is as [a-A-Z]-[0-9] to identify the prefix to keep) - and then sanitize that to get an identifier friendly enough to use in a version suffix.

Appreciate the 2nd is maybe a bit specific to my use case, I could have branches named "feature/ABCS-1234".  However, I think it's nice to be able to have branches that have a bit of description in them to orientate devs looking at git.

With the above a branch like "feature/ABCD-1234_some_helpful_text", I could set a template like
"{{#sanitizeLower}}{{#truncateAfterRegex}}{{#stripDirectory}}{{branch}}{{/stripDirectory}}{{/truncateAfterRegex}}{{/sanitizeLower}}"

and get "build-1.0.1-ABCD1234.1"

and I could put a release type specific prefix back in if I wanted by something like:
"feature{{#sanitizeLower}}{{#truncateAfterRegex}}{{#stripDirectory}}{{branch}}{{/stripDirectory}}{{/truncateAfterRegex}}{{/sanitizeLower}}"

to get "build-1.0.1-featureABCD1234.1"

The strip directory doesn't look too hard - as its all static.  But the regex one requires the config be passed to the function somehow

**Comment by flelli** [comment]
Hi @boardbloke ,

the second one is indeed a little trickier, but for the first one (strip), have you tried the [first](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/templates/#first) and [last](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/templates/#last) functions?

As far as I understand they do exactly what you need.

**Comment by boardbloke** [comment]
Hi @flelli ,

Yes.  If I have a branch like "feature/ABCD-1234_someText", then as per the example for [first](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/templates/#first) I'm going to get "feature"

If I try [last](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/templates/#last) then I get "someText"

I specifically want to strip the directory part.  My initial thought was what I wanted was to strip everything before the first occurrence of a non-alpha (i.e. the other half of the string than first provides), but actually that doesn't work if the directory has multiple levels or contains non-alphas, e.g. 'feature/qa-team/ABCD-1234_someText'

I thought the most useful to me and probably others was if there was a specific function to strip everything up to and including the last directory separator.

**Comment by flelli** [comment]
New functions `capture`, `cutLeft`, `cutRight`, `replace`, `timeFormat` have been implemented and will be available with the upcoming `2.0.0` release. See #138

**Comment by flelli** [comment]
Available in release [2.0.0](https://github.com/mooltiverse/nyx/releases/tag/2.0.0).
