### ISSUE TITLE
Clarify the documentation about extending the configuration for complex objects

### ISSUE THREAD

**Issue by flelli** [mooltiverse/nyx#121]
The documentation doesn't make it clear that overriding complex values in the configuration (i.e. `releaseTypes`, `commitMessageConventions`, `releaseAssets`, `services`), the whole item needs to be redefined in the extended configuration, not just its attributes.

See #118  for an example of the misleading instructions.

**Comment by boardbloke** [comment]
Hi @flelli ,

Thanks for the prompt response!  If that's the case then you might also wish to add a comment to the article https://levelup.gitconnected.com/semantic-release-automation-with-gradle-using-nyx-ba345235a365, as that seems to imply overriding sub properties of complex objects is possible?  

That was the gateway into this plugin (which is excellent by the way).  Out of interest, what is preventing overriding just some properties as per the article.  That seems like a nicer alternative if possible....

**Comment by flelli** [comment]
Ok, I'll update the Medium article as well.

Thanks for using it!
