### ISSUE TITLE
Help needed to setup Nyx with GitLab CI

### ISSUE THREAD

**Issue by Prototik** [mooltiverse/nyx#127]
First of all thanks for Nyx, it looks promising!

I cannot find more suitable place to request a help, so sorry about using GH issues for that.

I tried to setup Nyx for my new project on GitLab, but I cannot figure out why Nyx doesn't mark release on gitlab (and don't push tag at all). I setup personal access token with `api` and `write_repository` permissions and put it as `GITLAB_TOKEN` variable for CI.

My nyx config is [here](https://gitlab.com/kiscord/kitty/-/blob/master/.nyx.yaml). Latest job where `nyxMark` & `nyxPublish` tasks are executed is [here](https://gitlab.com/kiscord/kitty/-/jobs/3492907774).

I tried with different nyx configs, with and without `git.remotes` keys, it tried to mimic Nyx's config (with corrections GH -> GL for sure), it still silently skips tagging a release, and I cannot figure it why.

Does anyone have public sample of nyx with gitlab? Or can someone point me in the right direction why my config isn't working? Thank you in advance :+1:

**Comment by flelli** [comment]
Hi @Prototik ,

although running with increased verbosity like INFO or DEBUg may help, here's a couple of things I can see at a glance:

- the `mainline` release type can't be matched because:
  - it has the `matchWorkspaceStatus: "CLEAN"` option, which makes it match only when there are no untracked changes
  - the workspace is not clean as it has untracked changes, as per the output you get from running `git status`

By the way, remember to replace all occurrences of `environment.variable` (with the dot) to `environmentVariable` (camel case) in your configuration to make sure you can transition to version 2.0.0 safely.

**Comment by Prototik** [comment]
> it has the matchWorkspaceStatus: "CLEAN" option, which makes it match only when there are no untracked changes
Aha, I missed that point, thanks.

But there is one more step I required to do:
`git remote set-url origin "https://PRIVATE-TOKEN:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"` before release step, otherwise Nyx is trying to push using ci job token, which has no write_repository permission.

**Comment by Prototik** [comment]
@flelli Although I encountered another issue with release assets uploading.
[Here](https://github.com/mooltiverse/nyx/blob/f4e6a568f27d99d1578095b77dfae9f2e6a5ece1/modules/java/main/src/main/java/com/mooltiverse/oss/nyx/services/gitlab/RESTv4.java#L367) description of asset used as package name for GitLab's package registry.
[GitLab restricts package_name value](https://docs.gitlab.com/ee/user/packages/generic_packages/#publish-a-package-file) to be `[a-zA-Z0-9._-]+`, so human-readable description will break asset publication (one whitespace in asset description is enough).
I believe this is a mistake and here should be user asset name, not description. Can you confirm it?

**Comment by flelli** [comment]
> > it has the matchWorkspaceStatus: "CLEAN" option, which makes it match only when there are no untracked changes
> > Aha, I missed that point, thanks.
> 
> But there is one more step I required to do: `git remote set-url origin "https://PRIVATE-TOKEN:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"` before release step, otherwise Nyx is trying to push using ci job token, which has no write_repository permission.

I'm glad you solved the issue, however I have to point out that although setting the remote manually the way you did works, it means that the `$GITLAB_TOKEN` variable was not actually available to Nyx or that it lacks of some permissions/scopes. If it was, you didn't need to set the credentials in the remote URL.

**Comment by flelli** [comment]
> @flelli Although I encountered another issue with release assets uploading. [Here](https://github.com/mooltiverse/nyx/blob/f4e6a568f27d99d1578095b77dfae9f2e6a5ece1/modules/java/main/src/main/java/com/mooltiverse/oss/nyx/services/gitlab/RESTv4.java#L367) description of asset used as package name in the URL for GitLab's package registry. [GitLab restricts package_name value](https://docs.gitlab.com/ee/user/packages/generic_packages/#publish-a-package-file) to be `[a-zA-Z0-9._-]+`, so human-readable description will break asset publication (one whitespace in asset description is enough). I believe this is a mistake and here should be used asset name, not description. Can you confirm it?

Makes sense, however it's not much of a difference as you can set any values for both in Nyx's configuration.
The reasoj it's implemented this way is to make it as close as possible to other providers (namely GitHub right nuw, maybe more in the future).

**Comment by flelli** [comment]
Ok, I opened #128 for the release asset name so let's move that topic in there.

About the token, instead, I double checked and it's widely tested so I'm surprised of such behavior. Can you please send a DEBUG log so I can investigate?
Thanks

**Comment by Prototik** [comment]
> Can you please send a DEBUG log

How I can do that? Is Gradle's `--debug` flag is enough to do that?

**Comment by flelli** [comment]
Yes. Nyx will inherit verbosity from Gradle
