### ISSUE TITLE
BUG: Timestamp wrong in internal version and date wrong in "make" command

### ISSUE THREAD

**Issue by a-tom** [mooltiverse/nyx#131]
I encountered an error while creating a changelog for the release type internal. The timestamp in the version was wrong as well as the date in the changelog file after a "make" command.

This is because the function UnixMilli from the time go module is used although the EPOCH is given in seconds. The easy fix is to multiply the input to the function by 1000 in the following files:
- modules/go/nyx/command/make.go
- modules/go/nyx/template/functions.go

To get the tests working again, the file modules/go/nyx/template/functions_test.go needs to be adapted accordingly (input for the tests divided by 1000)

Alternatively the function "Unix" of the time module could be used, but then an additional "0" for the nanoseconds needs to be passed.
I only checked the go code, so I don't know if the same applies for the java code.

If you want, I can create a pull request.
Cheers, a-tom

**Comment by flelli** [comment]
Thanks a lot @a-tom , I'll fix it very soon and let you know when it's GA

**Comment by flelli** [comment]
Fixed as per version [1.3.1](https://github.com/mooltiverse/nyx/releases/tag/1.3.1)

The root cause was in the State object, and that also fixes the other unexpected bahaviors you mentioned.

Let me know
