### ISSUE TITLE
How are versions bumped?

### ISSUE THREAD

**Issue by riccardopinosio** [mooltiverse/nyx#181]
Hello,

I have a question regarding the package. I am trying to use it but I am a beginner at this versioning stuff and I'm a bit confused, as although the docs are great, there's a lot of info there and I'm not succeeding in finding a simple start with nyx, so maybe you can help :)

Basically I have a very simple scenario where I have a bunch of commits on the branch which do not follow any commit format. I would then like to start using nyx. When I do:

```
nyx --info
```

I get 

```
INFO[0000] Version: '0.1.0'
```

which makes sense: there's no tagged version before, so we start from the beginning.
However, when I add a commit with a message like

```
feat(ci/cd): start with versioning
```

I would expect nyx --info to return something like 0.2.0. Instead, the version is still 0.1.0.
From the docs, I suspect I have to run nyx mark to perform the action of tagging the new commit with the new version, but it doesn't seem to do it.

I'd appreciate some guidance on these simple things :)

**Comment by flelli** [comment]
Hi @riccardopinosio ,

it looks like you have no configuration in place so Nyx doesn't know what to do. Try following [this guide](https://mooltiverse.github.io/nyx/#getting -started-in-30-seconds), also passing --preset=simple to get started using a simple preset.

**Comment by riccardopinosio** [comment]
Hello,

`nyx --preset=simple infer` does not return any version number.
If i create a .nix.yaml in the project folder with

```
--- 
dryRun: false
initialVersion: "1.0.0"
preset: simple
releaseLenient: true
releasePrefix: v
scheme: "SEMVER"
verbosity: "WARNING"
```

as discussed in the examples, then nyx --preset-simple infer still doesn't return anything.
If I do

```
nyx --preset=simple --info infer
```

I then get 

```
INFO[0000] Version: '1.0.0'  
```

So it has detected the higher initial version, but still hasn't bumped the version based on the commit history.
My commit history is very simple, it has a bunch of non-structured commits with a last commit that has the message:

```
feat(ci/cd): start with versioning
```

Am I doing something wrong?

**Comment by flelli** [comment]
The version you get makes sense because you have no release tag yet. You will see that once you tag a first release and add some meaningful commits the version will be bumped.

Remember you also have the [state file](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/global-options/#state-file) you can use to check out Nyx' findings, or the --debug flag.

**Comment by riccardopinosio** [comment]
mm ok, so I should first manually tag a commit with the release (e.g. 'v1.0.0'), and then the commits after that one will be picked up and bump the version number? assuming I'm using the simple preset. It would seem the first tag needs to be manually added cause otherwise the mark command will not act, as infer hasn't detected any change?

**Comment by riccardopinosio** [comment]
cool, tagging the previous commit with 'v1.0.0' then makes nyx bump up the version to 1.1.0 when I do 

```
nyx --info infer
```

Interestingly however the command 

```
nyx --preset-simple infer
```
does the same thing but does not print the version.
I can then generate the changelong with nyx make, which returns

```
## v1.1.0-internal.1+timestamp.20230228115822 (2023-02-28)

### feat

* [] feat(cicd): adding .nix config (riccardo)
```

So that seems to work.
I would now be looking to create a release commit with the version tag.
As I'm using the simple preset, I would assume that nyx mark would create such a commit, as the [releaseTypes/mainline/gitTag](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#git-tag)
option is true. However the --debug comman (very useful!) gives me "the release type has the git tag flag disabled".

can you nudge me in the right direction here? :)

**Comment by flelli** [comment]
The version is printed at the `INFO` level, so if you want it printed keep using the `--info` argument.
"internal" is for non official releases, and it's an extra attribute defined in the release types that come preconfigured in the preset.

I think now it's time for you to check out the various configuration options so you can fine tune the configuration that better suits your needs.

**Comment by riccardopinosio** [comment]
Hi, yes, I figured it out! With the simple preset I was able to test the bumping of the version in the mainline release type (it was not tagging anything before because i was on a non-main branch, but once i tested it on the main branch everything worked as expected according to the "mainline" release type).
Thanks!

**Comment by sschuberth** [comment]
I'm sorry to chime in on this closed issue, but I'm also having difficulties to understand how `nyx` infers versions. For a history like

![image](https://github.com/mooltiverse/nyx/assets/349154/5a6b422a-df99-4ecd-a885-89e8549ac3d2)

`nyx --preset=simple infer --info` returns `time="2023-08-24T17:09:56+02:00" level=info msg="Version: '1.2.3'"`. But shouldn't the version inferred be higher than 1.2.3? I'm using nyx version 2.5.0-alpha.2.

**Comment by sschuberth** [comment]
> @sschuberth please refer to [this discussion](https://github.com/mooltiverse/nyx/discussions/256)

I'm sorry again, but I fail to understand how the concept of collapsed versioning plays a role here. If I already tagged version 1.2.3, and I have feature commits on top of it, the inferred version for a new release can under no circumstances also be 1.2.3.

**Comment by flelli** [comment]
Correct. Again, please switch to https://github.com/mooltiverse/nyx/discussions/256
