### ISSUE TITLE
Update package.json during the Mark or Make phase

### ISSUE THREAD

**Issue by AnakinPt** [mooltiverse/nyx#182]
I manage some projects using Nyx and gradle, even one npm project. I would like to use the Nyx to manage the version of the npm project, and I want to update the package.json file when a new version is created, so I can publish this package later on. Is this possible to do in an automated way using Nyx?

**Comment by flelli** [comment]
Good point and yes, it's definitely worth making Nyx update the `version` in the `package.json`.
Putting this in the backlog.
Thanks

**Comment by flelli** [comment]
Hi @AnakinPt ,

this feature is now available for preview in [2.5.0-alpha.1](https://github.com/mooltiverse/nyx/releases/tag/2.5.0-alpha.1)  and will be GA in the upcoming release [2.5.0](https://github.com/mooltiverse/nyx/releases/tag/2.5.0).

You can configure substitutions from scratch using the new [substitutions](https://github.com/mooltiverse/nyx/guide/user/configuration-reference/substitutions/) configuration options or, if you use the [extended preset](https://mooltiverse.github.io/nyx/guide/user/configuration-presets/extended/) you can simply [enable](https://github.com/mooltiverse/nyx/guide/user/configuration-reference/substitutions/#enabled) one of the [rules available out of the box](https://mooltiverse.github.io/nyx/guide/user/configuration-presets/extended/#substitutions), like Node (`package.json`), Rust (`Cargo.toml`), Helm (`Chart.yaml`), plain text (`version.txt`) and others.

**Comment by flelli** [comment]
Release [2.5.0](https://github.com/mooltiverse/nyx/releases/tag/2.5.0) is out. Changelog is [here](https://github.com/mooltiverse/nyx/blob/main/RELEASE_NOTES.md#250).
