### ISSUE TITLE
On Gitlab CI/CD, CI_COMMIT_BRANCH=main and plugin says Current branch '3cb2f4132543a82e4b45318c7d4566c94c62127b' 

### ISSUE THREAD

**Issue by javaworkinggirl** [mooltiverse/nyx#191]
Using a brand new gitlab project, the logs show a discrepancy between what Gitlab says the branch is versus what the plugin says the branch is.  The effect is that releaseType mistakenly resolves to internal instead of mainline.

The log showing what branch Gitlab says:
`
[32;1m$ echo "CI_COMMIT_BRANCH=$CI_COMMIT_BRANCH"[0;m
CI_COMMIT_BRANCH=main
`

The log showing what branch Nyx says:
`2023-03-30T16:30:27.761+0000 [DEBUG] [com.mooltiverse.oss.nyx.command.AbstractCommand] Current branch '3cb2f4132543a82e4b45318c7d4566c94c62127b' not matched by release type 'mainline' `

The whole log is attached.
[alpha.log](https://github.com/mooltiverse/nyx/files/11113986/alpha.log)

**Comment by javaworkinggirl** [comment]
And .gitlab-ci.yml has:
`  GIT_STRATEGY: clone
  GIT_DEPTH: "0"`

**Comment by flelli** [comment]
Hi @javaworkinggirl ,

as per [this issue](https://github.com/mooltiverse/nyx/issues/190), it seems your local repository is in a DETACHED HEAD state and you can tell by the current branch name (3cb2f4132543a82e4b45318c7d4566c94c62127b).
If you run `git branch` you sure can confirm this.

The GIT_STRATEGY: clone GIT_DEPTH: "0" is probably ignored or not declared the way it's supposed to. In any case it doesn't seem to take effect.

The `CI_COMMIT_BRANCH=main` is not the current local branch name but it's a variable used by GotLab's CI to set the branch that triggered the build.
