### ISSUE TITLE
can't get running bumping version

### ISSUE THREAD

**Issue by staehler** [mooltiverse/nyx#193]
Sorry to bother you. I studied the docs and tried some configurations, but can't find any solution for this strange behavior. So I hope someone can help me.

nyx creates a changelog, but it doesn't bump the release version, which stays since weeks on 0.4.0. There are lots of conventional commits in the history, but I always receive this message (excerpt), which means the previousVersion is v0.3.1 (which isn't, it's v0.4.0):

```
time="2023-04-06T06:53:36Z" level=debug msg="stepping by commit '93cff806b035133db746c2a998748a6d1893e3b8'"
time="2023-04-06T06:53:36Z" level=debug msg="commit '93cff806b035133db746c2a998748a6d1893e3b8' has '0' tags: '[]'"
time="2023-04-06T06:53:36Z" level=debug msg="commit history walk reached the end"
time="2023-04-06T06:53:36Z" level=debug msg="walking the commit history finished. The release scope contains 278 commits."
time="2023-04-06T06:53:36Z" level=debug msg="after scanning the commit history the previousVersion is 'v0.3.1'"
time="2023-04-06T06:53:36Z" level=debug msg="significant commits (bumping identifiers) since the previousVersion are '0'"
time="2023-04-06T06:53:36Z" level=debug msg="the commit history had no information about the primeVersion and primeVersionCommit but the release type doesn't use collapsed versioning, using the same values as the previousVersion and previousVersionCommit"
time="2023-04-06T06:53:36Z" level=debug msg="bumping component 'minor' on version '0.3.1'"
time="2023-04-06T06:53:36Z" level=debug msg="the release type does not define any (enabled) extra identifiers so none is applied"
time="2023-04-06T06:53:36Z" level=debug msg="computed version is: '0.4.0'"
time="2023-04-06T06:53:36Z" level=info msg="Version: 'v0.4.0'"
time="2023-04-06T06:53:36Z" level=debug msg="no version range check is required"
time="2023-04-06T06:53:36Z" level=debug msg="no version range check is performed"
time="2023-04-06T06:53:36Z" level=debug msg="version '0.4.0' did not require version range checks"
time="2023-04-06T06:53:36Z" level=debug msg="checking if version 'v0.4.0' is the latest in the repository"
time="2023-04-06T06:53:36Z" level=debug msg="retrieving all tags"
time="2023-04-06T06:53:36Z" level=debug msg="version 'v0.4.0' is the latest in the repository since no newer version has been found"
time="2023-04-06T06:53:36Z" level=debug msg="storing the Infer command internal attributes to the State"
time="2023-04-06T06:53:36Z" level=debug msg="repository latest commit in HEAD branch is '6a2f8dd24152a9b95f9e85f16d3f4c24963aa4cb'"
time="2023-04-06T06:53:36Z" level=debug msg="command 'INFER' finished."
```

The regarding configuration looks like, which is copied from [medium-configuration-example](https://mooltiverse.github.io/nyx/example/user/medium-configuration-example/) and little modified:

```
  "commitMessageConventions":{
    "enabled":[
      "conventionalCommits"
    ],
    "items":{
      "conventionalCommits":{
        "expression":"(?m)^(?<type>[a-zA-Z0-9_]+)(!)?(\\((?<scope>[a-z ]+)\\))?:( (?<title>.+))$(?s).*",
        "bumpExpressions":{
          "major":"(?s)(?m)^[a-zA-Z0-9_]+(!|.*^(BREAKING( |-)CHANGE: )).*",
          "minor":"(?s)(?m)^feat(?!!|.*^(BREAKING( |-)CHANGE: )).*",
          "patch":"(?s)(?m)^(fix|ci|perf|test)(?!!|.*^(BREAKING( |-)CHANGE: )).*"
        }
      }
    }
  },
```

My problem here it, that the `previousVersion is 'v0.3.1'` always stays at v0.3.1, although nyx bumped it to v0.4.0. 
In every new commit I'll find `previousVersion is 'v0.3.1'` and nyx bumps it up again to v0.4.0'.

I deleted tag v0.4.0 in gitlab, but it didn't change anything. v0.4.0 is created again and stays there :-(
![image](https://user-images.githubusercontent.com/6258158/230301724-2cdcc85f-b3d0-4d79-b321-38055a722241.png)

I'm quite sure, this must be a mistake by me, but I can't find a misconfiguration. Hope you can see anything there.
If you need further information, please let me know.

Thanks in advance and greetings

**Comment by flelli** [comment]
Hi @staehler ,

the issue seems that Nyx actually can't find the v4.0.0 tag in the local history. A couple of questions:

1. are you running this in a CI/CD pipeline? If so, are you [cloning the entire Git history](https://mooltiverse.github.io/nyx/guide/user/introduction/ci-cd/) or using the default?
2. is the v4.0.0 tag in the same branch of the commit you're running with? Or is it at least reachable, browsing commits backward, following the _first parent_ commit?

**Comment by staehler** [comment]
Thanks for your fast reply.

yes, I'm running it in a gitlab CI/CD, but I followed your advice and have my CI/CD defined like this:

```
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: "0"
    NYX_CONF_FILE: SemVer/.nyx.json
  before_script:
    - git checkout ${CI_COMMIT_BRANCH}
  script:
    - nyx --configuration-file=${NYX_CONF_FILE} --debug mark
```
But as you see, I need to checkout the ${CI_COMMIT_BRANCH}, otherwise gitlab point to HEAD, which won't be find in my nyx.json releaseTypes
```
  "releaseTypes":{
    "enabled":[
      "integration",
      "test"
    ],
    "publicationServices":[
      "gitlab"
    ],
    "remoteRepositories":[
      "origin"
    ],
    "items":{
      "integration":{
        "collapseVersions":false,
        "gitCommit":"true",
        "gitPush":"true",
        "gitTag":"true",
        "matchBranches":"^release$",
        "publish":"true"
      },
      "test":{
        "collapseVersions":false,
        "gitCommit":"true",
        "gitPush":"true",
        "gitTag":"true",
        "matchBranches":"^develop$",
        "publish":"true"
      }
    }
  },
```

To your second question, I'm no git expert, but I thought, tags are branch independent  But I also think the problem must be located anywhere within the branches, as the tag couldn't obviously not be read.

When I run nyx in my shell manually (without CI/CD), I find the same behavior, no version is bumped. I've checked out all the branches and I can see all tags listed

![image](https://user-images.githubusercontent.com/6258158/230323739-75bada35-53c0-40d7-9758-640ddd624a6a.png)

You can see an exceerpt of the git history:
- there is the `tag: v0.4.4` created at 08:32:12
- there is a conventional commit created at 10:33:05 `fix: remove test.txt`
=> no version changed

I reviewed the nyx debug output and it's quite interesting, the commit `2b5be05f0860e2639517baeb53921a8226775ed3` seems not to be available for nyx. This commit isn't shown in the debug messages and therefore the tag v0.4.0 is invisible for nyx. But I have no idea, what is happening here!?

How does nyx list all commits? Is there a filter?

**Comment by staehler** [comment]
So finally I can say, a `git log` shows the tag commit.
The nyx debug log doesn't show the tag commit.
I'm confused ...

Even, whe I delete the last tag and start again, nyx doesn't see the new bumped and created tag.

**Comment by flelli** [comment]
`git log` can show you commits in several orders, depending on the flags you pass.

Nyx always starts from the current commit (pointed by HEAD) and [goes backward](https://mooltiverse.github.io/nyx/example/user/git-history-examples/) until it has all the information it needs about past versions. When merge commits are encountered, the first parent commit only is followed.

I see you're using the _develop_ branch. Is it the same locally and on the GitLab runner?

I'm afraid the checkout strategy variables take no effect and, by the way, HEAD pointing to the latest commit is just ok. Can you run `git branch`and `git log` in the pipeline before running Nyx to see the output?

**Comment by staehler** [comment]
I'll be back with the answers after easter weekend.

But till then, one thought about HEAD. gitlab-runner checks out HEAD, which is in this case the output of `git branch` and therefore nyx won't do anything, as there is no directive configured for branch HEAD. Maybe github works different. But I didn't find another way, than to `git checkout develop` before running nyx. And maybe this is the problem in my case?

Anyway, now I want to wish you happy easter and have a good time!

**Comment by flelli** [comment]
HEAD is not an actual branch as it's just a symbolic link to the current commit

**Comment by flelli** [comment]
I believe the issue is in those two merge commits.

Can you add the `--first-parent` [option](https://marcgg.com/blog/2015/08/04/git-first-parent-log/) when you run `git log`? That way it will log commits following the [same logic as Nyx](https://mooltiverse.github.io/nyx/faq/user/how-does-nyx-deal-with-merge-commits-when-scanning-the-commit-history/).

**Comment by staehler** [comment]
Maybe I found a solution. I had to tweak this option https://docs.gitlab.com/ee/user/project/merge_requests/methods/ and use now the **"fast forward merge"**.

**Comment by flelli** [comment]
Ok, that means it's the merge method.
Consider that fast forward is not always possible but whichever merge strategy you use remember [this](https://mooltiverse.github.io/nyx/faq/user/how-does-nyx-deal-with-merge-commits-when-scanning-the-commit-history/).
