### ISSUE TITLE
Can't create Gitlab Release

### ISSUE THREAD

**Issue by lantier** [mooltiverse/nyx#198]
Thanks for developing NYX

So far, everything is doing good, with us releasing versions using only the `git.remote` feature.
However, we started to try releasing on `services.gitlab` as well and found what could be a possible bug:

Using the `REPOSITORY_OWNER` and `REPOSITORY_NAME` variables as `CI_PROJECT_NAMESPACE` and `CI_PROJECT_NAME` we receive the following (project name and namespace are redacted):

```
time="2023-04-28T19:26:15Z" level=debug msg="an error occurred while publishing GitLab release 'v1.1.0-RC.3': POST https://gitlab.com/api/v4/projects/MY_NAMESPACE>/<MY_PROJECT>/releases: 404 {message: 404 Project Not Found}"
could not publish GitLab release with tag 'v1.1.0-RC.3': POST https://gitlab.com/api/v4/projects/MY_NAMESPACE>/<MY_PROJECT>/releases: 404 {message: 404 Project Not Found}
```

Looking further on [API Documentation](https://docs.gitlab.com/ee/api/releases/#create-a-release) from GitLab, we found that the API expects an `:id` of the project instead of `:namespace/:project_name`.

GitLab withstands the whole path to the project if we use [an encoded path](https://docs.gitlab.com/ee/api/rest/index.html#namespaced-path-encoding) like `NAMESPACE%2FPROJECT`, and we tried to do that substituting `REPOSITORY_NAME` for this, without the `REPOSITORY_OWNER`parameter. 

However…
It failed because, from what I think, this line: https://github.com/mooltiverse/nyx/blob/0bea3243583528f59ee59e2dd45f88e1ddee10e3/modules/go/nyx/services/gitlab/gitlab.go#L535

It forces a `/` in between the two vars, so without the owner I have a request like:
`https://gitlab.com/api/v4/projects//MY_NAMESPACE>%2F<MY_PROJECT>/releases`

Which also fails because of the double slashes.
I know that it was an entire deep-dive, and I really like to know if I found a bug or there's an easy option or easy config that I'm not seeing here.

Thanks in advance

**Comment by flelli** [comment]
Hi @lantier ,

thanks for your effort investigating this.
It's likely a bug so let me check and get back to you soon.

**Comment by flelli** [comment]
I'm trying to find the bug but I guess I need some more info on your side. This piece  of code is extensively tested and I can't find the culprit so far.

As you said, [GitLab API](https://docs.gitlab.com/ee/api/releases/#create-a-release) (which we wrap behind [this library](https://pkg.go.dev/github.com/xanzy/go-gitlab#ReleasesService.CreateRelease)) requires _The ID or [URL-encoded path of the project](https://docs.gitlab.com/ee/api/rest/index.html#namespaced-path-encoding)._

The URL encoded path is `NAMESPACE/PROJECT_PATH` and that's what I pass to the API, which then does the encoding under the hood. I checked the logs from the tests and it works as expected.

Using `CI_PROJECT_NAMESPACE` and `CI_PROJECT_NAME` [CI variables](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html) should indeed be correct. I guess you redacted them for security/privacy reasons in the log statement you mentioned but did you check the URL is formed with the expected values and it's reachable?

Is there a chance you can send the debug logs or set up a public repo I can take a look at?

**Comment by flelli** [comment]
> I'm trying to find the bug but I guess I need some more info on your side. This piece of code is extensively tested and I can't find the culprit so far.
> 
> As you said, [GitLab API](https://docs.gitlab.com/ee/api/releases/#create-a-release) (which we wrap behind [this library](https://pkg.go.dev/github.com/xanzy/go-gitlab#ReleasesService.CreateRelease)) requires _The ID or [URL-encoded path of the project](https://docs.gitlab.com/ee/api/rest/index.html#namespaced-path-encoding)._
> 
> The URL encoded path is `NAMESPACE/PROJECT_PATH` and that's what I pass to the API, which then does the encoding under the hood. I checked the logs from the tests and it works as expected.
> 
> Using `CI_PROJECT_NAMESPACE` and `CI_PROJECT_NAME` [CI variables](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html) should indeed be correct. I guess you redacted them for security/privacy reasons in the log statement you mentioned but did you check the URL is formed with the expected values and it's reachable?
> 
> Is there a chance you can send the debug logs or set up a public repo I can take a look at?

Hi @lantier , any chance you can send these info?

**Comment by flelli** [comment]
Closing this issue due to lack of information. I'll reopen  when info is available
