### ISSUE TITLE
Services in Gradle Kotlin DSL

### ISSUE THREAD

**Issue by ennioVisco** [mooltiverse/nyx#211]
It is not clear how to use the services in Kotlin DSL syntax.

Groovy code:
```groovy
services {
    github {
      type = 'GITHUB'
      options {
        AUTHENTICATION_TOKEN = 'GITHUB_TOKEN'
        REPOSITORY_NAME = 'myrepo'
        REPOSITORY_OWNER = 'acme'
      }
    }
  }
```

More specifically, what does `services` take? 
Is `github` an identifier? and what type are the passed configurations?

**Comment by flelli** [comment]
Hi @ennioVisco ,

I'll add some Kotlin examples. Meanwhile:

- the service [name](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/services/#name) (lowercase `github`) is a name chosen by the user
- the service [type](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/services/#type) (uppercase `GITHUB`) is an identifier that must be chosen among available ones, namely `GITHUB` or `GITLAB` os of this writing

**Comment by ennioVisco** [comment]
This is probably the answer to the first question, but I have no clue about the second:
<img width="853" alt="image" src="https://user-images.githubusercontent.com/740025/237049367-4b68b1bb-0d71-4346-950d-613ce70ef255.png">

**Comment by flelli** [comment]
I'll have to investigate this myself as I'm no Kotlin expert and I never found any useful docs about translating Groovy configurations to Kotlin.

**Comment by ennioVisco** [comment]
> I'll have to investigate this myself as I'm no Kotlin expert and I never found any useful docs about translating Groovy configurations to Kotlin.

I have the opposite problem, so unfortunately I cannot help much, I found this guide somehow easier to understand: https://docs.gradle.org/current/userguide/kotlin_dsl.html#calling_groovy_from_kotlin
Syntax-wise there is no huge difference, the major difference is that Kotlin has explicit types, which means some constructs of groovy require wrapper functions and/or appropriate casting
