### ISSUE TITLE
feat: Update certain file content based on new version.

### ISSUE THREAD

**Issue by pysan3** [mooltiverse/nyx#223]
Hi, thank you very much for your amazing work!

Please kindly guide me to a documentation if this is already implemented.

## Feature

I would like to update the content of certain file with the new version.

My main usecase is to update the version notation for various programming language's packages.
For example, `python` packages are managed with [`pyproject.toml` > version](https://github.com/pysan3/MLTemplate/blob/d99a42656d4527228ebefa272fbf78dd53d846fb/pyproject.toml#L3) as well as the `nim` language also does something similar with [`package.nimble` > version](https://github.com/pysan3/tuicrown/blob/06c3c5a48e62a3bff683e6ad728b0c351cfa7455/tuicrown.nimble#L3).

I would like to update these numbers automatically with nyx.

### Alternatives

Over on `release-please` side, they detect the word `x-release-please-version` in the file and substitutes what seems to be a version number in that line. Something similar to this would be awesome.

https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files

### Possibly related

- https://github.com/mooltiverse/nyx/issues/182

Best,
pysan3

**Comment by flelli** [comment]
Hi @pysan3 ,

the feature is not yet available and you're right, it's very close to what is requested with https://github.com/mooltiverse/nyx/issues/182 so I definitely need to implement it as soon as I can.

Good to know these additional use cases so I can make it more generic and suitable for all use cases.

Also thanks for pointing me to [release-please](https://github.com/googleapis/release-please). I'll take a deeper look and try to make things consistent between the two.

**Comment by pysan3** [comment]
Thank you for your quick response @flelli !

Can't wait to see it implemented ;)

**Comment by flelli** [comment]
Thanks for the idea @rrzal , but I think that would be out of Nyx's scope as it would make it something like a build orchestrator. I mean, build scripts and their orchestration are something that can use Nyx, not the other way around.

Take Gradle for example, there is the Nyx plugin that is used by the build scripts, but doing the opposite would be conceptually wrong.

Long story short, my suggestion is using a build tool like Make, Gradle or anything else for the orchestration, and Nyx inside the scripts.

**Comment by flelli** [comment]
Hi @pysan3 ,

this feature is now available for preview in [2.5.0-alpha.1](https://github.com/mooltiverse/nyx/releases/tag/2.5.0-alpha.1)  and will be GA in the upcoming release [2.5.0](https://github.com/mooltiverse/nyx/releases/tag/2.5.0).

You can configure substitutions from scratch using the new [substitutions](https://github.com/mooltiverse/nyx/guide/user/configuration-reference/substitutions/) configuration options or, if you use the [extended preset](https://mooltiverse.github.io/nyx/guide/user/configuration-presets/extended/) you can simply [enable](https://github.com/mooltiverse/nyx/guide/user/configuration-reference/substitutions/#enabled) one of the [rules available out of the box](https://mooltiverse.github.io/nyx/guide/user/configuration-presets/extended/#substitutions), like Node (`package.json`), Rust (`Cargo.toml`), Helm (`Chart.yaml`), plain text (`version.txt`) and others.

**Comment by pysan3** [comment]
Thank you so so much @flelli!

I cannot be happier to see this feature being added and it'll drastically improve my workflow. 

I'll write you back when I'm able to test the new release (probly in a few days) but first of all thanks a lot for the hard work.

**Comment by flelli** [comment]
Release [2.5.0](https://github.com/mooltiverse/nyx/releases/tag/2.5.0) is out. Changelog is [here](https://github.com/mooltiverse/nyx/blob/main/RELEASE_NOTES.md#250).

**Comment by pysan3** [comment]
Hi @flelli,

Reading the docs, it says that I should define substitution patters at `substitutions/<name>/...` but looking at [this file](https://github.com/mooltiverse/nyx/blob/871412b0c3b4cbb98525c9352e0d887f37131787/docs/_includes/.nyx-extended.json) I think it should be `substitutions/items/<name>/...` (_items_ is missing), and the docs might need a fix.

When I use the latter path, it works as expected.

```json
{
  "preset": "extended",
  ...
  "substitutions": {
    "enabled": [
      "pyproject"
    ],
    "items": {
      "pyproject": {
        "files": "**/pyproject.toml",
        "match": "version = \"[0-9.]*\"\\s*# x-release-please-version",
        "replace": "version = \"{{version}}\" # x-release-please-version"
      }
    }
  }
}
```

**Comment by flelli** [comment]
Hi @pysan3 ,

thanks for your feedback. I guess you are referring to [this page](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/substitutions/). As you can see, the *Name* row says `substitutions/<NAME>/` as you said, because that's the generic name for the configuration option, but below, when it gives the *Configuration File Option* (which is what you used indeed) it says `substitutions/items/<NAME>/`.

Does it look correct to you?

**Comment by pysan3** [comment]
> but below, when it gives the Configuration File Option (which is what you used indeed) it says `substitutions/items/<NAME>/`.

Oh, you are right. Thanks!
