### ISSUE TITLE
Support of no fast forward merges

### ISSUE THREAD

**Issue by lxke19** [mooltiverse/nyx#235]
Hey @flelli ,

In our mainline we use no fast forward merges. This means nyx can't infer the correct version, due to the way it traverses the git history (first parent always).
Right now we use rebase+ff as a workaround to get the correct version, but by that we loose our merge commits and thus our correct commit graph.
The question is now, if there is a way to keep merge commits and have nyx infer the correct version. Do you plan to support this kind of situation?

Thanks in advance and BR,

Luke

**Comment by flelli** [comment]
Hi @lxke19 ,

the only way Nyx has to infer in this case is using the merge commit message. This means you need to give the merge commit a message that is significant in terms of version numbers to bump.

Any change [this issue](https://github.com/mooltiverse/nyx/issues/125) is of some interest to you?
