### ISSUE TITLE
`NoSuchMethodError` `Logger.isEnabledForLevel` when running `nyxMark` Gradle task

### ISSUE THREAD

**Issue by n8ebel** [mooltiverse/nyx#236]
## Environment Info
- nyx plugin version: 2.4.4-hotfix219.3
- gradle wrapper version: 8.2
- kotlin version: 1.8.0

** I replicated this in 2 separate projects.  One, that included additional dependencies such as ktor and another that was generated using `gradle init` and was a very minimal application project.

## Observed Behavior
- Running `./gradlew nyxInfer` or `./gradlew nyxMake` work fine.
- Running `./gradlew nyxMark` commits code and tags the commit as expected.  However, when trying to push to a configured remote via ssh, I'm getting the following error:

> Caused by: java.lang.NoSuchMethodError: 'boolean org.slf4j.Logger.isEnabledForLevel(org.slf4j.event.Level)'
        at com.mooltiverse.oss.nyx.git.JGitRepository$JschLogger.isEnabled(JGitRepository.java:296)
        at com.jcraft.jsch.Session.connect(Session.java:206)
        at org.eclipse.jgit.transport.ssh.jsch.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:123)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:107)
        at org.eclipse.jgit.transport.TransportGitSsh$SshPushConnection.<init>(TransportGitSsh.java:358)

## Investigation
- It appears that the plugin's implementation of `JGitRepository` relies on `slf4j 2.0.7` which includes the `Logger.isEnabledForLevel`.
- [Gradle's `Logger`](https://docs.gradle.org/current/javadoc/org/gradle/api/logging/Logger.html) extends the slf4j Logger, but does not include a `isEnabledForLevel` method.
- I attached a breakpoint at `JGitRepository.java:296` and inspected the source location for the logger instance which was reported as coming from the gradle wrapper's logging jar
> ~/.gradle/wrapper/dists/gradle-8.2-bin/bbg7u40eoinfdyxsxr3z4i7ta/gradle-8.2/lib/gradle-logging-8.2.jar
- At the same line, evaluating the source location for slfrj `Logger` indicates that the dependency is coming from gradle and that it's using version `1.7.30` which does not include a `isEnabledForLevel` method
> ~/.gradle/wrapper/dists/gradle-8.2-bin/bbg7u40eoinfdyxsxr3z4i7ta/gradle-8.2/lib/slf4j-api-1.7.30.jar
- While I haven't encountered this, if this _is_ an issue of mismatched slf4j version, it looks like there could be a similar issue with `JGitRepository.java:308` and `logger.atLevel()` as well

Misc other notes:
- Applying the plugin from `build.gradle.kts` didn't seem to change the behavior versus applying from `settings.gradle.kts`

## Questions
- Is there an existing sample project somewhere that includes a Gradle Plugin configuration that I could examine and compare to?  I didn't see one.
- This seems like something that would be impacting any user of the Gradle Plugin which makes me wonder if it's something specific to my configuration, but I don't see anything obvious that would be causing this.  I'm not aware of any way to force dependency resolution on the slf4j version coming from the gradle wrapper itself.

**Comment by flelli** [comment]
Hi @n8ebel ,

thanks for the super detailed info, you saved me a lot of time.

I couldn't reproduce locally but I just published release [2.4.5](https://github.com/mooltiverse/nyx/releases/tag/2.4.5) and I'm pretty sure it's fixed. Can you give it a try?

**Comment by n8ebel** [comment]
I was just writing up a response to thank you for the quick fix when I saw your comment 🙂

Yes, definitely.  I'll try this out this afternoon and let you know how it goes.

**Comment by n8ebel** [comment]
I tried it out.  I can confirm that the original issue I reported is fixed 👍🏼 

However, I'm now running into a new issue.
> Caused by: java.lang.NoSuchMethodError: 'org.slf4j.spi.LoggingEventBuilder org.slf4j.Logger.atLevel(org.slf4j.event.Level)'
        at com.mooltiverse.oss.nyx.git.JGitRepository$JschLogger.log(JGitRepository.java:313)
        at com.jcraft.jsch.Session.connect(Session.java:207)
        at org.eclipse.jgit.transport.ssh.jsch.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:123)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:107)
        at org.eclipse.jgit.transport.TransportGitSsh$SshPushConnection.<init>(TransportGitSsh.java:358)

I mentioned this in the original post that I _thought_ it could be an issue even though I had not encountered it up to that point.  
> While I haven't encountered this, if this is an issue of mismatched slf4j version, it looks like there could be a similar issue with JGitRepository.java:308 and logger.atLevel() as well

I've pushed my small sample project in case that helps to repro the issue:
https://github.com/n8ebel/nyx-sandbox


## Possible Solution
I cloned the repo, changed how these 2 logging methods were implemented, published the plugin to mavenLocal, and re-ran my project and was able to move past these logging issues.  

```
@Override
        public boolean isEnabled(int level){
            Level logLevel = levelMapping.get(Integer.valueOf(level));
            switch (logLevel) {
                case ERROR:
                    return logger.isErrorEnabled();
                case WARN:
                    return logger.isWarnEnabled();
                case INFO:
                    return logger.isInfoEnabled();
                case DEBUG:
                    return logger.isDebugEnabled();
                case TRACE:
                    return logger.isTraceEnabled();
            }

            return false;
        }

        /**
         * Logs the given message at the given level, relaying to SLF4J.
         * 
         * @param level one of the log level constants DEBUG, INFO, WARN, ERROR and FATAL
         * 
         * @return {@code true} if the logging for the given level is enabled
         */
        @Override
        public void log(int level, String message){
            Level logLevel = levelMapping.get(Integer.valueOf(level));
            switch (logLevel) {
                case ERROR:
                    logger.error(message);
                    break;
                case WARN:
                    logger.warn(message);
                    break;
                case INFO:
                    logger.info(message);
                    break;
                case DEBUG:
                    logger.debug(message);
                    break;
                case TRACE:
                    logger.trace(message);
                    break;
            }
        }
    }
```


## Questions

1. Would it be helpful if I submitted a separate issue for this?
2. How do you feel about these logging changes?  If they seem reasonable to you, I could submit a PR if that would save you time.

**Comment by flelli** [comment]
Thanks @n8ebel ,

I'm cooking a quick fix embedding your suggestions

**Comment by flelli** [comment]
@n8ebel , I just published [2.4.6-hotfix236.1](https://github.com/mooltiverse/nyx/releases/tag/2.4.6-hotfix236.1).
Can you give it a try before I merge to main?

**Comment by n8ebel** [comment]
@flelli  Just tested it out in my sandbox project and that fix is looking good.  No longer having any issues with the `nyxMark` task when using `PUBLIC_KEY` authentication method 👍🏼 👍🏼

**Comment by flelli** [comment]
@n8ebel , it's now GA as [2.4.6](https://github.com/mooltiverse/nyx/releases/tag/2.4.6)
