### ISSUE TITLE
GitHub releases features

### ISSUE THREAD

**Issue by ennioVisco** [mooltiverse/nyx#238]
I think it would be cool to better integrate with GitHub releases more specifically:

- [ ] having the ability to mark them as `pre-releases` (possibly linked to pre-releases identifiers, see: https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#collapse-versions:~:text=PRE_RELEASE%3A%20the%20identifier%20appears%20in%20the%20pre%2Drelease%20part).
- [ ] having the ability to not mark them as `latest release` (this is usually common for pre-releases and could as well be linked to them)
- [ ] controlling the actual name of the release (we can currently control prefixes via `releasePrefix`, but it would be cool if we could also add some `releasePostfix` possibly containing strings (e.g. codenames) and/or short templates (e.g. release date).

**Comment by ennioVisco** [comment]
I think it would combine very well with the `PRE-RELEASE` option: https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#collapse-versions:~:text=PRE_RELEASE%3A%20the%20identifier%20appears%20in%20the%20pre%2Drelease%20part

**Comment by flelli** [comment]
Hi @ennioVisco ,

just checked the [underlying library](https://github-api.kohsuke.org/) to implement the feature and I will build the `pre-release/draft` option soon.

Unfortunately the library doesn't give me control on the _latest_ release flag but my first guess is that a release marked as _draft_ or _pre-release_ won't be marked automatically as _latest_.

I'll also add another option to set the release name.

**Comment by ennioVisco** [comment]
Amazing! I'll gladly help testing :)

Probably you're right about the latest release, let's see how it will work!

**Comment by flelli** [comment]
Hi @ennioVisco ,

these features are on their way. They will be available in preview in [2.5.0-alpha.3](https://github.com/mooltiverse/nyx/releases/tag/2.5.0-alpha.3) ([still building](https://github.com/mooltiverse/nyx/actions/runs/5975697044) as I'm writing but I need to leave the keyboard so it's there for your reference) and they will be generally available in the upcoming [2.5.0](https://github.com/mooltiverse/nyx/releases/tag/2.5.0).

You can control the name of the release by means of the new [`releaseName`](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#release-name) configuration option inside the release type configuration (links to the docs will work when the final release will be published).

Likewise, still in the release type configuration, you have the [`publishPreRelease`](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#publish-pre-release) template (needs to evaluate to a boolean, but you can set it straight to `true`) to flag releases as _pre-release_.

I can confirm when you mark a release as `pre-release` it's not marked as `latest`.

**Comment by flelli** [comment]
Release [2.5.0](https://github.com/mooltiverse/nyx/releases/tag/2.5.0) is out. Changelog is [here](https://github.com/mooltiverse/nyx/blob/main/RELEASE_NOTES.md#250).
