### ISSUE TITLE
Gradle NyxExtension options typo

### ISSUE THREAD

**Issue by alinturbut** [mooltiverse/nyx#240]
While trying to integrate the Gradle Extension, I've realized that the interface has a typo which can be tricky to stop while setting the options:

`geOptions() -> getOptions()` 

```
        /**
         * Returns the map of service options.
         * 
         * @return the map of service options.
         */
        public MapProperty<String,String> geOptions() {
            return options;
        }
```

location: https://github.com/mooltiverse/nyx/blob/57e8b588fb4a84c5e5526edf093a3c7d3fc2c9fc/modules/java/gradle/src/main/java/com/mooltiverse/oss/nyx/gradle/NyxExtension.java#L1840

Created a Pull-Request to address it here: https://github.com/mooltiverse/nyx/pull/241

**Comment by flelli** [comment]
Thanks a lot @alinturbut ,

I created another PR so I also updated the docs but the fix will be available as [2.4.7](https://github.com/mooltiverse/nyx/releases/tag/2.4.7) as soon as the pipeline completes (just kicked as I'm writing)
