### ISSUE TITLE
`nyx --preset=simple infer` should show the version (only) even without `--info`

### ISSUE THREAD

**Issue by sschuberth** [mooltiverse/nyx#254]
With `nyx` version 2.5.0-alpha.2, in the same [project](https://github.com/oss-review-toolkit/ort) (with a single locally created lightweight tag named "v1.2.3"), `nyx --preset=simple infer` outputs nothing, whereas `./gradlew nyxInfer` shows

    > Task :nyxInfer
    Project version: 1.2.3

Shouldn't these commands behave the same?

**Comment by sschuberth** [comment]
Ok, [looks like](https://github.com/mooltiverse/nyx/issues/181) passing `--info` is required to make `nyx` print the version. But shouldn't that be the default behavior for `nyx infer` even without `--info`? Also, *only* the version should be shown, without any `INFO` log prefix or so, to be able to easily pipe the version output to somewhere.

**Comment by sschuberth** [comment]
BTW, [Getting Started](https://github.com/mooltiverse/nyx?tab=readme-ov-file#getting-started-in-30-seconds) also suggests that `nyx --preset=simple infer` would print the version, but it doesn't.

**Comment by flelli** [comment]
When using Gradle the log verbosity is controlled by Gradle, which defaults to `info`.

Use the [summary](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/global-options/#summary) if you need consistent output to parse.

**Comment by sschuberth** [comment]
> Use the [summary](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/global-options/#summary) if you need consistent output to parse.

Mind at least adjusting [Getting Started](https://github.com/mooltiverse/nyx?tab=readme-ov-file#getting-started-in-30-seconds) then? Because this output is then not true:

    $ nyx --preset=simple infer
    Version: 1.2.3
