### ISSUE TITLE
Removing complying prefixes from commits

### ISSUE THREAD

**Issue by ennioVisco** [mooltiverse/nyx#259]
I was curious whether there is a way (I didn't get it from the docs) to remove the prefixes of the commits complying to the commits policy (I'm thinking in particular about the prefixes as shown in the following screenshot from `nyx` releases):

![Screenshot 2023-08-29 at 15 18 38](https://github.com/mooltiverse/nyx/assets/740025/82ef5ba8-05b8-4d92-9cb7-c3f9d66b1b19)

**Comment by flelli** [comment]
Hi @ennioVisco ,

no, there's no such option as of now. What you can use, at most, is [substitutions](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/changelog/#substitutions) so you can mangle each line by using regular expressions.

Would this be a feature for you?

**Comment by ennioVisco** [comment]
> Hi @ennioVisco ,
> 
> no, there's no such option as of now. What you can use, at most, is [substitutions](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/changelog/#substitutions) so you can mangle each line by using regular expressions.
> 
> Would this be a feature for you?

I was thinking about the substitutions indeed. 
I wouldn't say I need this feature. Perhaps a substitution is fine as of now, and maybe one day a preset can be made available if others also seem to prefer this option 😊

**Comment by flelli** [comment]
Wait @ennioVisco , there's a better option than substitutions. . Regular expressions need a try but you can achieve that with standard features.

Use a custom changelog [template](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/changelog/#template) and use some [function](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/templates/#the-functions-library) like [`capture`](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/templates/#capture) to mangle the commit row title.

For example, replace the [default changelog template](https://raw.githubusercontent.com/mooltiverse/nyx/main/modules/java/main/src/main/resources/changelog.tpl) lines:

```
{{#commits}}
* [{{#short5}}{{SHA}}{{/short5}}] {{message.shortMessage}} ({{authorAction.identity.name}})
```

with:

```
{{#commits}}
* [{{#short5}}{{SHA}}{{/short5}}] {{#capture expression="(?<type>[a-zA-Z0-9_]+)(!)?(\((?<scope>[a-z ]+)\))?:( (?<title>.+))" group="title"}}{{message.shortMessage}}{{/capture}} ({{authorAction.identity.name}})
```

This function extracts the `title` named group from the `{{message.shortMessage}}` so it's exactly what you need here. Again, I haven't tested this expression but all the features are there.

**Comment by ennioVisco** [comment]
> Wait @ennioVisco , there's a better option than substitutions. . Regular expressions need a try but you can achieve that with standard features.
> 
> Use a custom changelog [template](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/changelog/#template) and use some [function](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/templates/#the-functions-library) like [`capture`](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/templates/#capture) to mangle the commit row title.
> 
> For example, replace the [default changelog template](https://raw.githubusercontent.com/mooltiverse/nyx/main/modules/java/main/src/main/resources/changelog.tpl) lines:
> 
> ```
> {{#commits}}
> * [{{#short5}}{{SHA}}{{/short5}}] {{message.shortMessage}} ({{authorAction.identity.name}})
> ```
> 
> with:
> 
> ```
> {{#commits}}
> * [{{#short5}}{{SHA}}{{/short5}}] {{#capture expression="(?<type>[a-zA-Z0-9_]+)(!)?(\((?<scope>[a-z ]+)\))?:( (?<title>.+))" group="title"}}{{message.shortMessage}}{{/capture}} ({{authorAction.identity.name}})
> ```
> 
> This function extracts the `title` named group from the `{{message.shortMessage}}` so it's exactly what you need here. Again, I haven't tested this expression but all the features are there.

Thanks, I am already using a custom template, so this is a good idea, I didn't think about it!
One question though, just because I am not sure whether it is a bug:
by using your line I get this: https://github.com/ennioVisco/webmonitor/releases/tag/v1.1.0-internal.1.beta.12 (notice the broken commit links)... Could it be the capturing does not happen just on the inner `message.shortMessage` but changes the whole line?

**Comment by flelli** [comment]
That's weird, I need to test.

Are you using the Java/Gradle or the Go/Command Line version?

**Comment by ennioVisco** [comment]
> That's weird, I need to test.
> 
> Are you using the Java/Gradle or the Go/Command Line version?

I'm using the github action, so I guess the Go/Command Line

**Comment by ennioVisco** [comment]
> That's weird, I need to test.
> 
> Are you using the Java/Gradle or the Go/Command Line version?

With a more careful analysis, I think the problem is different, and there is a problem with the new version in detecting state variables, in particular:

- `{{#short5}}{{SHA}}{{/short5}}` is returning an empty string in `changelog.hbs` (in `#releases.#sections.#commits`)
- "releaseName": "{{version}} ({{#timeFormat format=\"yyyyMMdd\"}}{{/timeFormat}})"` or `"releaseName": "{{version}} ({{#timeFormat format=\"yyyyMMdd\"}} {{timestamp}} {{/timeFormat}})"` are giving the format string, like there is no timestamp, while version is readable, in `.nyx.json`, section `releaseTypes.items.$RELEASE_ITEM_NAME.releaseName`

**Comment by ennioVisco** [comment]
There is a difference with the latest release, where `{{SHA}}` was previously case insensitive while it now needs to be lower case `{{sha}}`. Fixing this it works as expected
