### ISSUE TITLE
Problem with MergeCommit implementation

### ISSUE THREAD

**Issue by lxke19** [mooltiverse/nyx#271]
Hey @flelli ,

we really apreciate your help with the merge commits. But it still doesn't work for us. We tried it with the extended preset:
"
override fun apply(project: Project) {
        project.pluginManager.apply(NyxPlugin::class.java)
        project.extensions.configure(NyxExtension::class.java) { nyxExtension ->
            nyxExtension.preset.set("extended")
            // This commitMessageConvention, configures nyx to support merge commits instead of rebase and fast-forward merges
            nyxExtension.commitMessageConventions.enabled.set(
                listOf(
                    "conventionalCommitsForMerge"
                )
            )
            nyxExtension.dryRun.set(false)
            nyxExtension.releaseLenient.set(true)
...
"
as well as with the simple preset:
"
 nyxExtension.commitMessageConventions { convention ->
                convention.items { item ->
                    item.create("mergeCommitConvention") { mergeCommitConvention ->
                        mergeCommitConvention.expression.set("""(?<type>[a-zA-Z0-9_]+)(!)?\((?<scope>[a-z ]+)\)?:( (?<title>.+))""")
                        val commitMessageExpressions = mapOf(
                            "major" to """(?s)(?m)[a-zA-Z0-9_]+(!: .*|.*^(BREAKING( |-)CHANGE: )).*""",
                            "minor" to """(?s)(?m)feat(!{0})(\([a-z ]+\))?: (?!.*^(BREAKING( |-)CHANGE: )).*""",
                            "patch" to """(?s)(?m)fix(!{0})(\([a-z ]+\))?: (?!.*^(BREAKING( |-)CHANGE: )).*"""
                        )
                        mergeCommitConvention.bumpExpressions.set(commitMessageExpressions)
                    }
                }
            }
"
What could be our Problem we enabled it as you said. Or did I missunderstand something?

Thanks in advance,

Luke

**Comment by flelli** [comment]
Can you give me an example repo pr commit message and debug log message?

**Comment by lxke19** [comment]
Ah we now understand, how you're trying to solve this problem with merge commits. Unfortunately this solution doesn't work for us. We use Gitea and in it's merge commits there is no way to include the commit messages of al the commits in the branch. As we understand it, you are trying to get the version number from the merge commit itself, but the first parent rule remains. But that doesn't work for us. If you plan to revisit the merge commits issue so that nyx follows both parents and uses logic to infer the version, please let us know. Nevertheless, a big thank you for your efforts.

**Comment by flelli** [comment]
Ok, so this is related to https://github.com/mooltiverse/nyx/issues/270

**Comment by flelli** [comment]
I'm closing this issue as it's merged to https://github.com/mooltiverse/nyx/issues/270
