### ISSUE TITLE
Infer version from specified previous version

### ISSUE THREAD

**Issue by mist3r3** [mooltiverse/nyx#286]
Hi team, I would like to infer the new vesion from a specific version, what is the best way to do that?

For example if I have a commit message with "feat: ****"

In my pipeline I would like to specify from which version it should calculate the next one, like an option:
--previous-version="1.0.0". I don't want to use git tags for the versioning.
After nyx infer it would give me "1.1.0"

Thanks!

**Comment by flelli** [comment]
Hi @mist3r3 ,

if you're not using tags the [initial version](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/global-options/#initial-version) option is probably what you're looking for.

**Comment by mist3r3** [comment]
Hi @flelli, I do have tags with the version, it's just I do not want to use it.
How can I make nyx to ignore the tags and just use the previous version? Should I create a wrong regex?
Thanks!

**Comment by flelli** [comment]
Well, that use case is kind of out of scope for Nyx. You can override the [version](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/global-options/#version) but I see it's not what you're looking for.
The problem is that for your use case Nyx doesn't know how to scope the commit history to compute the new version.

**Comment by mist3r3** [comment]
Can I make it ignore the commit history?
Else my other solution would be like I said (I checked), to add a wrong regex there so it won't take any tag and use the initVersion.

**Comment by flelli** [comment]
You can't ignore the commit history, you can only tweak it by, as you said, alter the regex that matches past version tags.
However I wouldn't go down that way unless it's just a one shot, and if it is, I'd rather compute a version and apply the tag manually then start using Nyx from then on.
