### ISSUE TITLE
contradicting documentation and examples regarding `publish` and `publishPreRelease`

### ISSUE THREAD

**Issue by sh-cau** [mooltiverse/nyx#301]
[In the documentation](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#publish-pre-release:~:text=this%20decision%20dynamic.-,This%20option%20only%20takes%20effect%20when%20publish%20evaluates%20true.,-Release%20name) it says that publishing a prerelease is only possible when `publish: true`. 
But at the same time, [in the examples](https://mooltiverse.github.io/nyx/example/user/extended-configuration-example/#:~:text=publish%3A%20%22false%22%0A%20%20%20%20%20%20publishPreRelease%3A%20%22true%22) there's a (senseless) example where `publish: false` and `publishPreRelease: true`.

**Comment by flelli** [comment]
Hi @sh-cau ,

thanks for finding the confusing example in the docs. In that example `publish: false` has priority over `publishPreRelease: true` so no publication happens.
However, the example may be misleading and I'll fix it.
