### ISSUE TITLE
Incorrectly declared Java compatibility for version 3.x

### ISSUE THREAD

**Issue by piotrminkina** [mooltiverse/nyx#302]
Hello,

I noticed that you are using the target compatibility for Java 11, but you are also using dependencies for higher Java compatibility (in this case Java 17). I've read that in version 3.0.0 support for Java versions older than 17 was dropped, but there was a missing configuration.

https://github.com/mooltiverse/nyx/blob/a7e73b3eb69c1f080323df5bf031961f449a9b24/modules/java/build.gradle#L151

Regards
Piotr Minkina

**Comment by flelli** [comment]
Thanks @piotrminkina , I forgot to change that, I'll fix it soon
