### ISSUE TITLE
Misleading configuration for extended configuration example in the docs: `gitCommit: false` with `gitCommitMessage: "Release version {{version}}"`

### ISSUE THREAD

**Issue by sh-cau** [mooltiverse/nyx#311]
[In the documentation](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#git-commit-message:~:text=This%20option%20is%20ignored%20when%20gitCommit%20is%20false.) it says that `gitCommitMessage` is ignored when `gitCommit: false`. However, [in the extended configuration example](https://mooltiverse.github.io/nyx/example/user/extended-configuration-example/#:~:text=gitCommit%3A%20%22false%22%0A%20%20%20%20%20%20gitCommitMessage%3A%20%22Release%20version%20%22), this combination is used.

**Comment by flelli** [comment]
Fixed in the upcoming release once [this](https://github.com/mooltiverse/nyx/pull/344) PR has been merged.

For future reference, the docs page has moved [here](https://mooltiverse.github.io/nyx/docs/resources/examples/extended-configuration-example) with the new documentation site.
