### ISSUE TITLE
Add support for monorepo's containing multiple components making use of tags being filtered by a tagPrefix

### ISSUE THREAD

**Issue by jan-van-de-pol** [mooltiverse/nyx#322]
We use a gradle project in a repo that also contains helm charts with a different lifecycle, and thereby another version. For this we make use of prefixes for the tags to seperate them during our Semantic Releasing. Would be great if we can use Nyx and add some tagPrefix to it's configuration to filter only the relevant tags in our case.

I have created a patch to enable this (for the Java side of things):
[featureTagPrefix.patch](https://github.com/user-attachments/files/16815413/featureTagPrefix.patch)

Hope that you will find this usefull and integrate into your great Semantic Release tool!

**Comment by jan-van-de-pol** [comment]
Just found out about filterTags. Looks like my initial case can be solved with that.

**Comment by flelli** [comment]
Ok, I'm closing this issue then

**Comment by jan-van-de-pol** [comment]
There is still an issue to filter out commits that only apply to a subset of files and folders. Currently all commits are taken into account, while monorepo support would only take into account the commits that apply to the component being build. We currently have 2 variants here.

Example repo 1:
- component1
- component2

Example repo 2:
- (component1 on root level)
- component2
