### ISSUE TITLE
Issue building in container using github actions using nyx gradle plugin.

### ISSUE THREAD

**Issue by dnamaz** [mooltiverse/nyx#325]
I have a build.yml GA that uses a java image, eclipse-temurin:23-noble.

`jobs:
  build:
    runs-on: self-hosted-runner
    container:
      image: eclipse-temurin:23-noble

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        shell: bash
        run: |
          ./gradlew nyxInfer
`
I get the following error message: (app = repository)
> The directory '/__w/app/app' is not accessible or does not contain a valid Git repository.

I've tried various other java images all with the same problem. Not sure if anyone has information on how to get by this? My build.gradle and settings.gradle use the nyx plugin. 

Only way that I can get around this is not use the gradle plugin, but the github action.

**Comment by flelli** [comment]
Hi @dnamaz ,

it looks clearly specific to the image you're using. Specifically it seems the current directory is not set to the Git folder. You can try to:

- set the [directory](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/global-options/#directory) configuration option to the directory where the Git repository has been checked out
- use an Ubuntu image
