### ISSUE TITLE
support git connection via SSH key

### ISSUE THREAD

**Issue by mr-pineapple-nz** [mooltiverse/nyx#94]
Currently the git remote connection can only use:
- username/password with https checkout
- generated tokens of GitLab/Github

Would be nice to have using SSH keys with an SSH agent when it comes to push anything to the remote.

**Comment by flelli** [comment]
Thanks @mr-pineapple-nz , I'll keep this for the backlog

**Comment by capitanh** [comment]
I support this. I've being banging my head against a wall trying to find out why tags are not pushed to remote, until I tried checking our as https instead of ssh...

**Comment by flelli** [comment]
Ok, I'll add support for SSH right after releasing the command line version of the tool

**Comment by flelli** [comment]
Feature has been implemented and will be generally available in the upcoming release `2.0.0`.
Beware of some JVM limitations as from release `2.0.0` the minimum JVM version is 15.

**Comment by flelli** [comment]
Available in release [2.0.0](https://github.com/mooltiverse/nyx/releases/tag/2.0.0).
