### ISSUE TITLE
Gradle (Kotlin) unable to resolve reference nyx in settings.gradle.kt file

### ISSUE THREAD

**Issue by aharshbarger** [mooltiverse/nyx#98]
I'm running into issues with a Java project that is using Gradle (Kotlin) DSL.  The issue occurs after adding the plugin to the `settings.gradle.kts` file and applying.  I get  (`Unresolved reference: nyx`) when trying to use the `nyx` configuration block.  

Using IntelliJ IDEA 2021.3.1, Gradle Wrapper 7.4, JDK 17 (also tried it with JDK 11)

```
plugins {
    id("com.mooltiverse.oss.nyx") version "1.0.1-fix81.1"
}

nyx {
    // define configurations here
}
```

If I use the `nyx.yml` file instead, it works as expected.

**Comment by flelli** [comment]
Thanks @aharshbarger .
I'm no Kotlin master but I'll try to sort it out. Can you please send me a simplified build script to reproduce the error?

**Comment by Prototik** [comment]
It can be configure in that way:
```kotlin
extensions.configure<NyxExtension>("nyx") {
   // configuration goes here
}
```

**Comment by flelli** [comment]
I managed to have the plugin working with Kotlin both as a _project_ and as a _settings_ plugin.

The _project plugin_ configuration (`build.gradle.kts`) is:

```kotlin
plugins {
  id("com.mooltiverse.oss.nyx") version "1.3.4"
}

nyx {
  dryRun.set(false)
  resume.set(false)
  stateFile.set(".nyx-state.yml")
  verbosity.set("DEBUG")
}
```

While the _settings plugin_ configuration (`settings.gradle.kts`) is:

```kotlin
plugins {
  id("com.mooltiverse.oss.nyx") version "1.3.4"
}

configure<com.mooltiverse.oss.nyx.gradle.NyxExtension> {
  dryRun.set(false)
  resume.set(false)
  stateFile.set(".nyx-state.yml")
  verbosity.set("DEBUG")
}
```

I also added these to the documentation.

Again, I'm no Kotlin expert so other suggestions and contributions are welcome.

**Comment by ennioVisco** [comment]
@flelli this solution should be mentioned in the docs [here](https://mooltiverse.github.io/nyx/guide/user/quick-start/gradle-plugin/), when using Kotlin DSL, which is now the preferred gradle scripts language (https://blog.gradle.org/kotlin-dsl-is-now-the-default-for-new-gradle-builds)

> It can be configure in that way:
> 
> ```kotlin
> import com.mooltiverse.oss.nyx.gradle.NyxExtension
> 
> plugins {
>     id("com.mooltiverse.oss.nyx") version "1.3.0"
> }
> 
> extensions.configure<NyxExtension>("nyx") {
>    // configuration goes here
> }
> ```

**Comment by flelli** [comment]
It's already documented [here](https://mooltiverse.github.io/nyx/guide/user/introduction/usage/#apply-the-plugin)
